# Generated by Django 3.2.9 on 2022-01-23 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autodkgzhu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=32, null=True, verbose_name='邮箱'),
        ),
    ]
